[package]
name = "Cyprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.11"
iced_web = "0.4.0"
zip = "0.6"
quick-xml = "0.31.0"
scraper = "0.17.1"
