[package]
name = "Cyprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.23.0", features = ["serde", "color-hex"] }
zip = "0.6"
quick-xml = "0.31.0"
